cl_league_leaguetable_list:
    resource: "@CLLeagueBundle/Resources/config/routing/leaguetable.yml"
    prefix:   /leaguetable/list

cl_league_round_list:
    resource: "@CLLeagueBundle/Resources/config/routing/round.yml"
    prefix:   /round/list

cl_league_game:
    resource: "@CLLeagueBundle/Resources/config/routing/game.yml"
    prefix:   /game/list

cl_league_news:
    resource: "@CLLeagueBundle/Resources/config/routing/news.yml"
    prefix:   /news/list

CLLeagueBundle_player:
    resource: "@CLLeagueBundle/Resources/config/routing/player.yml"
    prefix:   /player/list

cl_league_league:
    resource: "@CLLeagueBundle/Resources/config/routing/league.yml"
    prefix:   /league/list

CLLeagueBundle_team:
        resource: "@CLLeagueBundle/Resources/config/routing/team.yml"
        prefix:   /team/list
    
cl_league_homepage:
    path:     /hello/{name}
    defaults: { _controller: CLLeagueBundle:Default:index }

cl_homepage:
    path:     /
    defaults: { _controller: CLLeagueBundle:Homepage:homepage }    
  
cl_ouroffer:
    path:    /ouroffer
    defaults:   
        _controller: FrameworkBundle:Template:template 
        template: CLLeagueBundle::ouroffer.html.twig
       
cl_facilities:
    path:    /facilities
    defaults:   
        _controller: FrameworkBundle:Template:template 
        template: CLLeagueBundle::facilities.html.twig        

cl_about:
    path:    /about
    defaults:   
        _controller: FrameworkBundle:Template:template 
        template: CLLeagueBundle::about.html.twig
    
cl_show_league:
    path:    /league/{id}
    defaults:
        _controller: CLLeagueBundle:League:showLeague
        template: CLLeagueBundle:League:showLeague.html.twig
        id: 1

cl_show_team:
    path:    /team/{id}
    defaults:
        _controller: CLLeagueBundle:Team:showTeam
        template: CLLeagueBundle:Team:showTeam.html.twig        
        id: 1

cl_show_player:
    path:    /player/{id}
    defaults:
        _controller: CLLeagueBundle:Player:showPlayer
        template: CLLeagueBundle:Player:showPlayer.html.twig
        id: 1        

cl_show_all_teams:
    path:   /teams
    defaults:
        _controller: CLLeagueBundle:Team:showAllTeams
        template: CLLeagueBundle:Team:showAllTeams.html.twig
        
cl_show_news:
    path:   /news/{id}
    defaults:
        _controller: CLLeagueBundle:News:showNews
        template: CLLeagueBundle:News:showNews.html.twig 
        id: 1       

cl_register_team:
    path:   /register
    defaults:
        _controller: CLLeagueBundle:Team:registerTeam
        template: CLLeagueBundle:Team:registerTeam.html.twig        
        